### ISSUE TITLE
/docs layout

### ISSUE THREAD

**Issue by Reasno** [DoNewsCode/core-starter#2]
- /docs 如果有swagger文件index.html以及js，css就好了。
- docs下面也可能有其他格式的文档，比如docify，那么可以用/docs/swagger和/docs/docify来区分。
- 可以用go 1.16的//go:embed 来打包文档。

**Comment by nfangxu** [comment]
swagger 和 docsify 加上了  go:embed 我再看看

**Comment by nfangxu** [comment]
#13
